# This is a basic workflow to help you get started with Actions

name: CI

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: distroless/actions/apko-publish@main
        id: apko
        with:
          config: caddy.yaml
          tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: cosign-installer
        # You may pin to the exact commit or the version.
        # uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a
        uses: sigstore/cosign-installer@v3.8.1
        #with:
          # cosign release version to be installed
          #cosign-release: # optional, default is v2.4.3
          # Where to install the cosign binary
          #install-dir: # optional, default is $HOME/.cosign
          # set to true if install-dir location requires sudo privs
          #use-sudo: # optional, default is false
                
      - run: cosign sign --yes ${{ steps.apko.outputs.digest }}
